# Generated by Django 2.1.3 on 2018-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipoLocal', models.TextField(max_length=30)),
                ('EquipoVisitante', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='equipo_ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=10)),
                ('Ciudad', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='goles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golesLocal', models.TextField(max_length=10)),
                ('golesVisitante', models.TextField(max_length=10)),
            ],
        ),
    ]
